Repository python-ring-doorbell/python-ring-doorbell, pull requests merged in 2019-12, with the labels that each got.

#152 OAuth Fixes
  .gitignore
  requirements.txt
  ring_doorbell/__init__.py
  ring_doorbell/auth.py
  ring_doorbell/const.py
  ring_doorbell/generic.py
  ring_doorbell/stickup_cam.py
  test.py
  tox.ini
Labels: PRIORITY, bug

#165 Implemented timeouts for HTTP requests methods
  ring_doorbell/__init__.py
  ring_doorbell/const.py
Labels: enhancement, feature_requested

#167 Use auth expires_in to refresh oauth tokens
  ring_doorbell/__init__.py
Labels: bug, enhancement
