Repository python-ring-doorbell/python-ring-doorbell, pull requests merged in 2020-01, with the labels that each got.

#172 Video download fix
  ring_doorbell/__init__.py
  ring_doorbell/const.py
  ring_doorbell/doorbot.py
Labels: bug

#175 Auth and ring class refactor
  README.rst
  ring_doorbell/__init__.py
  ring_doorbell/auth.py
  ring_doorbell/chime.py
  ring_doorbell/const.py
  ring_doorbell/doorbot.py
  ring_doorbell/generic.py
  ring_doorbell/utils.py
  setup.py
  test.py
  tests/test_base.py
  tests/test_ring.py
  tests/test_ring_utils.py
Labels: enhancement, help wanted

#180 Removed otp_callback
  ring_doorbell/auth.py
  test.py
Labels: enhancement
