Repository python-ring-doorbell/python-ring-doorbell, pull requests merged in 2024-09, with the labels that each got.

#419 Fix method to enable in-home doorbell chime
  ring_doorbell/doorbot.py
  tests/test_ring.py
Labels: bugfix

#423 Fix active listen alert counter
  ring_doorbell/ring.py
  tests/conftest.py
  tests/fixtures/listen/camera_motion_analytics.json
  tests/fixtures/listen/camera_motion_android_config.json
  tests/fixtures/listen/camera_motion_data.json
  tests/fixtures/listen/camera_motion_gcmdata.json
  tests/fixtures/listen/camera_motion_img.json
  tests/fixtures/listen/doorbot_ding_gcmdata.json
  tests/fixtures/listen/fcmdata_v1.json
  tests/fixtures/listen/fcmdata_v2.json
  tests/fixtures/listen/intercom_ding_analytics.json
  tests/fixtures/listen/intercom_ding_android_config.json
  tests/fixtures/listen/intercom_ding_data.json
  tests/fixtures/listen/intercom_unlock_gcmdata.json
  tests/test_cli.py
  tests/test_listen.py
Labels: bugfix

#348 Add WebRTC live streaming session generation
  poetry.lock
  pyproject.toml
  ring_doorbell/const.py
  ring_doorbell/doorbot.py
  ring_doorbell/ring.py
  ring_doorbell/rtcstream.py
Labels: no-stale

#432 Prepare 0.9.4
  CHANGELOG.md
  pyproject.toml
  uv.lock
Labels: release-prep

#433 Upgrade artifact upload/download github actions
  .github/workflows/publish.yml
Labels: maintenance

#434 Fix publish workflow action
  .github/workflows/publish.yml
Labels: maintenance

#443 Prepare 0.9.5
  CHANGELOG.md
  pyproject.toml
  uv.lock
Labels: release-prep

#445 Event listener capability enabled by default
  .github/workflows/ci.yml
  README.rst
  pyproject.toml
  ring_doorbell/__init__.py
  ring_doorbell/cli.py
  ring_doorbell/listen/__init__.py
  tests/conftest.py
  tests/test_cli.py
  tests/test_listen.py
  uv.lock
Labels: enhancement

#448 Prepare 0.9.6
  CHANGELOG.md
  pyproject.toml
  uv.lock
Labels: release-prep
