Repository python-ring-doorbell/python-ring-doorbell, pull requests merged in 2024-08, with the labels that each got.

#378 Small change to modify the timestamp
  .vscode/settings.json
  poetry.lock
  pyproject.toml
  ring_doorbell/generic.py
  ring_doorbell/listen/eventlistener.py
  ring_doorbell/util.py
  tests/test_ring.py
Labels: stale

#408 Prepare 0.9.0
  .github_changelog_generator
  CHANGELOG.md
  pyproject.toml
Labels: release-prep

#415 Prepare 0.9.1
  CHANGELOG.md
  pyproject.toml
Labels: release-prep

#416 Fix event listener
  poetry.lock
  pyproject.toml
  ring_doorbell/cli.py
  ring_doorbell/const.py
  ring_doorbell/doorbot.py
  ring_doorbell/listen/eventlistener.py
  ring_doorbell/other.py
  ring_doorbell/ring.py
  tests/conftest.py
  tests/fixtures/ring_listen_credentials.json
  tests/test_cli.py
  tests/test_listen.py
Labels: bugfix
