Repository python-ring-doorbell/python-ring-doorbell, pull requests merged in 2024-11, with the labels that each got.

#463 Fix doorbell elite missing capabilities
  ring_doorbell/doorbot.py
Labels: bugfix

#464 Add new push notification intercom unlock
  ring_doorbell/const.py
Labels: bugfix

#466 Prepare 0.9.10
  CHANGELOG.md
  pyproject.toml
  ring_doorbell/webrtcstream.py
  uv.lock
Labels: release-prep

#467 Add is_update flag to ring events for updated events
  ring_doorbell/event.py
  ring_doorbell/listen/eventlistener.py
  tests/test_cli.py
Labels: enhancement

#468 Prepare 0.9.11
  CHANGELOG.md
  pyproject.toml
  uv.lock
Labels: release-prep

#471 Prepare 0.9.12
  CHANGELOG.md
  pyproject.toml
  uv.lock
Labels: release-prep

#474 Support new Battery Doorbell device
  ring_doorbell/const.py
  ring_doorbell/doorbot.py
Labels: new-device
